DROP TABLE IF EXISTS customer_authorities;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS order_status;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_creator;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS shipping_address;



CREATE TABLE IF NOT EXISTS authority
(
    authority_id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    authority_name varchar(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS customer
(
    customer_id  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name   varchar(50)          NOT NULL,
    last_name    varchar(50)          NOT NULL,
    login        varchar(50)          NOT NULL,
    password     varchar(255)         NOT NUll,
    email        varchar(100)         NOT NULL,
    date_created date                 NOT NULL,
    date_updated date,
    is_enabled   boolean DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_authorities
(
    customer_authorities_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id             int NOT NULL REFERENCES customer (customer_id) ON DELETE CASCADE,
    authority_id            int NOT NULL REFERENCES authority (authority_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS product_category
(
    category_id     int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name   varchar(50) NOT NULL,
    parent_category int REFERENCES product_category (category_id),
    level           int         NOT NULL
);

CREATE TABLE IF NOT EXISTS product_creator
(
    creator_id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creator_name  varchar(100) NOT NULL,
    email_address varchar(50)  NOT NULL,
    img_src       varchar      NOT NULL
);

CREATE TABLE IF NOT EXISTS product
(
    product_id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name    varchar(100)  NOT NULL,
    product_code    varchar(11)   NOT NULL,
    category        int           NOT NULL REFERENCES product_category (category_id) ON DELETE CASCADE,
    creator         int           NOT NULL REFERENCES product_creator (creator_id) ON DELETE CASCADE,
    description     text          NOT NULL,
    date_created    date          NOT NULL,
    amount_on_stock int           NOT NULL CHECK ( amount_on_stock >= 0 ),
    price           numeric(6, 2) NOT NULL,
    img_src         varchar       NOT NULL
);

CREATE TABLE IF NOT EXISTS shipping_address
(
    address_id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    department         int          NOT NULL,
    department_address varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cart
(
    cart_id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer      int        NOT NULL REFERENCES customer (customer_id),
    product       int        NOT NULL REFERENCES product (product_id),
    amount        int        NOT NULL CHECK ( amount >= 1 AND amount <= 20 ),
    product_price numeric(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_status
(
    status_id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status_name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id     int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address      int        NOT NULL REFERENCES shipping_address (address_id),
    products     int        NOT NULL REFERENCES cart (cart_id),
    total_price  numeric(2) NOT NULL,
    date_created date       NOT NULL,
    order_status int        NOT NULL REFERENCES order_status (status_id)
);