spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webmart
    username: postgres
    password: ENC(8v+lEc0mmziy7U7yoAkbhQ==)
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db.migration
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webmart
    user: postgres
    password: ENC(8v+lEc0mmziy7U7yoAkbhQ==)
    schemas: public
    default-schema: public
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jasypt:
  encryptor:
    password: ${ENCRYPTION_SECRET}
    algorithm: ${ENCRYPTION_ALGORITHM}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator